connection:
  port: 25570 # Порт для подключения
  available: '127.0.0.1' # Запросы с других IP-адресов будут выведены в консоль
  print_not_available: true # Сообщить о сторонних подключениях. Полезно при настройке
actions: # Команды при действии. Auto для самостоятельного решения плагина
  level: 'HP' # Вариант того, что будет отправлено на пульт (HP, LEVEL, TIME). По умолчанию 'HP'
  k1: 'auto'
  k2: 'auto'
  k3: 'auto'
  k4: 'auto'
  k5: 'auto'
  k6: 'auto'
  k7: 'auto'
  red_key: 'auto'